[tool.black]
target-version = ["py311"]
line-length = 88

[tool.ruff]
line-length = 88
target-version = "py311"
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # flake8-bugbear
    "B",
    # flake8-annotations
    "A",
    # isort
    "I",
]
ignore = [
    "F401", # unused-import
    "E741", # anbiguous-variable-name
]

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.mypy]
python_version = "3.11.9"
platform = "linux"
disallow_untyped_defs = true
ignore_missing_imports = true
allow_redefinition = true

[tool.pyright]
exclude = [
    "data",
    "datasets",
    "outputs",
    "media",
    "**/.mypy_cache",
    "**/.cache",
    "**/.git",
    "**/.hypothesis",
    "**/__pycache__",
    "**/site-packages",
]
stubPath = "stubs"
typeCheckingMode = "off"
reportPrivateImportUsage = "none"
